export const theme = {
  black: '#000',
  white: '#fff',
  beige: '#ffe0c5',
  grey: '#555',
  regular: 400,
  light: 300,
  xxl: '60px',
  xl: '44px',
  l: '30px',
  m: '18px',
  s: '16px',
  xs: '14px',
  xxs: '12px',
  headingFont: `'Alegreya', 'Arial', sans-serif`,
  bodyFont: `'Lato', 'Arial', sans-serif`,
};
