export const theme = {
  black: '#000',
  white: '#fff',
  beige: '#ffe0c5',
  grey: '#6a6a6a',
  lightGrey: '#aaa',
  regular: 400,
  light: 300,
  xxxxl: '120px',
  xxxl: '64px',
  xxl: '50px',
  xl: '34px',
  l: '26px',
  m: '20px',
  sm: '18px',
  s: '16px',
  xs: '14px',
  xxs: '12px',
  headingFont: `'Alegreya', 'Arial', sans-serif`,
  bodyFont: `'Lato', 'Arial', sans-serif`,
  lineHeightXl: 2,
  lineHeightL: 1.8,
  lineHeightM: 1.6,
  lineHeightS: 1.4,
  lineHeightXs: 1.2,
  maxWidth: '1200px',
};
